import { Accommodation, SinaiTrip } from '@/lib/types'
import { PLACEHOLDER_IMAGES } from '@/lib/constants'

export const MOCK_ACCOMMODATIONS: Accommodation[] = [
  {
    id: '1',
    name_ar: 'فندق دهب برادايس',
    name_en: 'Dahab Paradise Hotel',
    type: 'hotel',
    description_ar: 'فندق 3 نجوم مطل على البحر الأحمر ومجاور لجبال سيناء. يتميز بـ حمام سباحة خارجي، مطعم، وغرف مكيفة بالكامل مع بلكونة خاصة.',
    description_en: '3-star hotel overlooking the Red Sea and Sinai mountains. Features an outdoor pool, restaurant, and air-conditioned rooms with private balconies.',
    images: [PLACEHOLDER_IMAGES.dahab1, PLACEHOLDER_IMAGES.dahab2, PLACEHOLDER_IMAGES.dahab3],
    rating: 4,
    location: 'المسبط، دهب',
    amenities_ar: ['حمام سباحة', 'واي فاي مجاني', 'إفطار مجاني', 'إطلالة على البحر', 'تكييف'],
    amenities_en: ['Swimming Pool', 'Free WiFi', 'Free Breakfast', 'Sea View', 'Air Conditioning'],
    price_per_night: 850,
    price_4day: 3200,
    price_5day: 3900,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name_ar: 'شاليهات لاجونا بيتش',
    name_en: 'Laguna Beach Chalets',
    type: 'chalet',
    description_ar: 'شاليهات صف أول على البحر في منطقة اللاجونا. مناسبة للعائلات والمجموعات، تحتوي على مطبخ مجهز وحديقة خاصة.',
    description_en: 'First-line chalets on the beach in the Laguna area. Suitable for families and groups, features a fully equipped kitchen and private garden.',
    images: [PLACEHOLDER_IMAGES.dahab2, PLACEHOLDER_IMAGES.dahab3, PLACEHOLDER_IMAGES.dahab1],
    rating: 5,
    location: 'اللاجونا، دهب',
    amenities_ar: ['مطبخ مجهز', 'حديقة خاصة', 'مباشرة على البحر', 'شواية باربيكيو', 'واي فاي'],
    amenities_en: ['Equipped Kitchen', 'Private Garden', 'Beachfront', 'BBQ Grill', 'WiFi'],
    price_per_night: 1200,
    price_4day: 4100,
    price_5day: 4950,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name_ar: 'كامب علي بابا البدوية',
    name_en: 'Ali Baba Bedouin Camp',
    type: 'camp',
    description_ar: 'تجربة بدوية أصيلة على شاطئ المسبط. غرف خشبية بسيطة ومريحة، جلسات بدوية ليلية مع الشاي البدوي والموسيقى.',
    description_en: 'Authentic Bedouin experience on Masbat beach. Simple cozy wooden rooms, evening Bedouin seating with tea and music.',
    images: [PLACEHOLDER_IMAGES.camping, PLACEHOLDER_IMAGES.desert1, PLACEHOLDER_IMAGES.dahab3],
    rating: 4,
    location: 'المسبط، دهب',
    amenities_ar: ['جلسة بدوية', 'مباشرة على البحر', 'شاي بدوي مجاني', 'أجواء عائلية', 'مقهى شاطئي'],
    amenities_en: ['Bedouin Seating', 'Beachfront', 'Free Bedouin Tea', 'Cozy Vibe', 'Beach Cafe'],
    price_per_night: 450,
    price_4day: 2100,
    price_5day: 2600,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name_ar: 'فندق تروبيتيل دهب أواسيز',
    name_en: 'Tropitel Dahab Oasis Hotel',
    type: 'hotel',
    description_ar: 'منتجع 4 نجوم فاخر بين جبال سيناء وخليج العقبة. يقع بالقرب من منطقة البلو هول العالمية للغوص.',
    description_en: 'Luxury 4-star resort set between Sinai mountains and Gulf of Aqaba. Located near the world-famous Blue Hole diving spot.',
    images: [PLACEHOLDER_IMAGES.dahab3, PLACEHOLDER_IMAGES.diving, PLACEHOLDER_IMAGES.dahab1],
    rating: 5,
    location: 'منطقة البلو هول، دهب',
    amenities_ar: ['حمام سباحة دافء', 'مركز غوص خاص', 'شاطئ خاص', 'جيم وسبا', 'بوفيه مفتوح'],
    amenities_en: ['Heated Pool', 'Private Dive Center', 'Private Beach', 'Gym & Spa', 'Open Buffet'],
    price_per_night: 1500,
    price_4day: 5200,
    price_5day: 6300,
    is_active: true,
    created_at: new Date().toISOString(),
  },
]

import { CommunityPost } from '@/lib/types'

export const MOCK_COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: '1',
    title_ar: 'دليل المبتدئين للغوص في دهب',
    title_en: 'Beginner\'s Guide to Diving in Dahab',
    content_ar: 'دهب من أفضل أماكن الغوص في العالم. البحر الأحمر بيضم شعاب مرجانية استثنائية وحطام سفن تاريخية. في البوست ده هنتكلم عن أفضل مراكز الغوص المعتمدة، الأسعار، ونصائح للمبتدئين قبل ما تنزل المية لأول مرة.',
    content_en: 'Dahab is one of the best diving spots in the world. The Red Sea hosts exceptional coral reefs and historical shipwrecks. In this post, we\'ll cover the best certified dive centers, prices, and beginner tips before your first dive.',
    category: 'blog',
    image_url: 'https://images.unsplash.com/photo-1544551763-92ab472dec22?w=1200&q=80',
    sort_order: 1,
    is_pinned: true,
    is_published: true,
    created_at: '2026-07-15T10:00:00Z',
  },
  {
    id: '2',
    title_ar: 'الوادي الملون — جوهرة مخفية في سيناء',
    title_en: 'Colored Canyon — A Hidden Gem in Sinai',
    content_ar: 'الوادي الملون من أجمل الأماكن اللي معظم السياح بيفوتوها. 30 كم من دهب، ممرات صخرية ضيقة بألوان مذهلة من الأحمر والبرتقالي والأصفر. الرحلة مناسبة لكل الأعمار وبتاخد حوالي 4-5 ساعات كاملة.',
    content_en: 'The Colored Canyon is one of the most beautiful places most tourists miss. 30km from Dahab, narrow rock passages in stunning red, orange & yellow colors. Suitable for all ages, takes 4-5 hours total.',
    category: 'hidden-gems',
    image_url: 'https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3?w=1200&q=80',
    sort_order: 2,
    is_pinned: false,
    is_published: true,
    created_at: '2026-07-20T10:00:00Z',
  },
  {
    id: '3',
    title_ar: 'قصة عميل: رحلتي الأولى لدهب مع First Trip',
    title_en: 'Customer Story: My First Dahab Trip with First Trip',
    content_ar: 'من 4 سنين وأنا عايز أزور دهب. شفت الصور والكلام الحلو بس مكنتش عارف أبدأ منين. صحبي رشّح First Trip. حجزت باكدج 4 أيام من القاهرة. كل حاجة كانت مظبوطة من الأول للآخر — الانتقالات، الفندق، وحتى الرحلتين الإضافيتين. شكراً First Trip!',
    content_en: 'I\'ve wanted to visit Dahab for 4 years. I saw the pictures and heard good things but didn\'t know where to start. My friend recommended First Trip. I booked a 4-day package from Cairo. Everything was perfect — transfers, hotel, even the bonus trips. Thanks First Trip!',
    category: 'stories',
    image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80',
    sort_order: 3,
    is_pinned: false,
    is_published: true,
    created_at: '2026-07-25T10:00:00Z',
  },
  {
    id: '4',
    title_ar: 'أفضل 10 مطاعم في دهب',
    title_en: 'Top 10 Restaurants in Dahab',
    content_ar: 'دهب عندها مشهد أكل متنوع ومميز جداً. من المطاعم المصرية التقليدية للمأكولات البحرية الطازة للأكل البدوي الأصلي. هنا قمنا هنرشحلك أحسن 10 أماكن تنفع لكل ميزانية.',
    content_en: 'Dahab has a diverse and unique food scene. From traditional Egyptian restaurants to fresh seafood to authentic Bedouin cuisine. Here are our top 10 picks for every budget.',
    category: 'dahab-guide',
    image_url: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=1200&q=80',
    sort_order: 4,
    is_pinned: false,
    is_published: true,
    created_at: '2026-08-01T10:00:00Z',
  },
]

export const MOCK_SINAI_TRIPS: SinaiTrip[] = [
  {
    id: '1',
    name_ar: 'رحلة البلو هول وسنوركلينج',
    name_en: 'Blue Hole & Snorkeling Trip',
    description_ar: 'زيارة أشهر موقع غوص وسنوركلينج في العالم، مع جولة بيتش باجي (سفاري) ووجبة غداء بدوية على الشاطئ.',
    description_en: 'Visit the world-famous diving and snorkeling spot, including quad bike safari and a Bedouin lunch on the beach.',
    category_ar: 'مغامرات وبحر',
    category_en: 'Adventure & Sea',
    images: [PLACEHOLDER_IMAGES.dahab2, PLACEHOLDER_IMAGES.diving],
    duration: 'يوم كامل (8 ساعات)',
    price: 450,
    includes_ar: ['انتقالات من وإلى الفندق', 'معدات السنوركل', 'غداء بدوي', 'مرشد سياحي'],
    includes_en: ['Hotel Transfers', 'Snorkeling Gear', 'Bedouin Lunch', 'Tour Guide'],
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name_ar: 'صعود جبل موسى ودير سانت كاترين',
    name_en: 'Mount Sinai & St. Catherine Monastery',
    description_ar: 'رحلة ليلية لصعود جبل موسى ومشاهدة شروق الشمس من قمة الجبل، ثم زيارة دير سانت كاترين الأثري.',
    description_en: 'Night trek up Mount Sinai to watch the breathtaking sunrise from the summit, followed by a visit to St. Catherine Monastery.',
    category_ar: 'رحلات دينية وجبلية',
    category_en: 'Religious & Mountain Trek',
    images: [PLACEHOLDER_IMAGES.mountain, PLACEHOLDER_IMAGES.desert2],
    duration: 'رحلة ليلية (12 ساعة)',
    price: 650,
    includes_ar: ['انتقالات بباص حديث', 'دليل بدوي مرخص', 'تذاكر دخول المحمية', 'مشروب دافئ'],
    includes_en: ['Modern Bus Transfer', 'Licensed Bedouin Guide', 'Reserve Entry Tickets', 'Hot Drink'],
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name_ar: 'سفاري وادي وشواشي والوشواشي',
    name_en: 'Wadi Wishwashi Safari',
    description_ar: 'رحلة جيب 4x4 بين الممرات الصخرية الضيقة للوصول إلى المسبح الطبيعي المخبأ وسط الجبال والسباحة فيه.',
    description_en: '4x4 Jeep trip through narrow rock canyons to reach the hidden natural freshwater pool in the mountains.',
    category_ar: 'سفاري وأماكن مخفية',
    category_en: 'Safari & Hidden Gems',
    images: [PLACEHOLDER_IMAGES.desert1, PLACEHOLDER_IMAGES.desert2],
    duration: 'نصف يوم (5 ساعات)',
    price: 500,
    includes_ar: ['سيارات جيب 4x4', 'دليل خبير', 'مياه ومشروبات', 'غداء بدوي'],
    includes_en: ['4x4 Jeep Transportation', 'Expert Guide', 'Water & Drinks', 'Bedouin Lunch'],
    is_active: true,
    created_at: new Date().toISOString(),
  },
]
