import { Accommodation, SinaiTrip } from '@/lib/types'
import { PLACEHOLDER_IMAGES } from '@/lib/constants'

export const MOCK_ACCOMMODATIONS: Accommodation[] = [
  /* ═══════════════ Budget ═══════════════ */
  {
    id: '1', name_ar: 'تورينو كامب', name_en: 'Torino Camp', type: 'camp', tier: 'budget',
    description_ar: 'كامب cozy وهادي في قلب ممشى دهب السياحي — المكان المثالي للباكبكرز والمسافرين اللي بيدوروا على vibes حقيقية مش تكلفة. خطوات من البحر وكل كافيهات اللايت هاوس، وغرف مريحة ونضيفة بديكور boho modern chic.',
    description_en: 'A cozy, laid-back camp in the heart of Dahab\'s promenade — the perfect spot for backpackers and travelers looking for real vibes, not just a room. Steps from the sea and all the Lighthouse cafes, with comfy, clean boho-modern rooms.',
    images: [PLACEHOLDER_IMAGES.dahab1, PLACEHOLDER_IMAGES.dahab2], rating: 4.2,
    location: 'الممشى السياحي · اللايت هاوس · دهب', location_ar: 'الممشى السياحي · اللايت هاوس · دهب', location_en: 'Promenade · Lighthouse · Dahab',
    amenities_ar: ['واي فاي', 'قعدات بدوية', 'قريب من البحر', 'تكييف'], amenities_en: ['WiFi', 'Bedouin Seating', 'Near Beach', 'AC'],
    price_per_night: 650, price_4day: 2650, price_5day: 3200, is_active: true, created_at: new Date().toISOString(),
  },
  {
    id: '2', name_ar: 'فندق أنتيكا', name_en: 'Antika Hotel', type: 'hotel', tier: 'budget',
    description_ar: 'فندق صغير بحمام سباحة في قلب الممشى — جنب محطة Go Bus. قعدات بدوية مريحة بروح دهب الأصيلة، وغرف نظيفة وبسيطة. مناسب جداً للجروبات والصحاب اللي عايزين مكان نضيف وقريب من كل حاجة.',
    description_en: 'A small hotel with a pool right in the heart of the promenade — next to Go Bus station. Comfortable Bedouin-style seating with authentic Dahab spirit, clean simple rooms. Perfect for groups who want a clean place close to everything.',
    images: [PLACEHOLDER_IMAGES.dahab2, PLACEHOLDER_IMAGES.dahab3], rating: 4.0,
    location: 'الممشى السياحي · جنب Go Bus · دهب', location_ar: 'الممشى السياحي · جنب Go Bus · دهب', location_en: 'Promenade · Near Go Bus · Dahab',
    amenities_ar: ['حمام سباحة', 'واي فاي', 'قعدات بدوية', 'تكييف'], amenities_en: ['Swimming Pool', 'WiFi', 'Bedouin Seating', 'AC'],
    price_per_night: 800, price_4day: 3300, price_5day: 4100, is_active: true, created_at: new Date().toISOString(),
  },
  {
    id: '3', name_ar: 'موخيتو بالم', name_en: 'Mojito Palm', type: 'hotel', tier: 'budget',
    description_ar: 'صف أول على البحر مباشرة — الكافيه والإفطار بيطلوا على المياه الفيروزية. جنب الكوبري الخشبي أشهر spot تصوير في دهب. غرف مريحة وإطلالة بحر، والفطار اختياري في كافيه موخيتو الشهير.',
    description_en: 'First row directly on the sea — the café and breakfast overlook turquoise waters. Next to the wooden bridge, Dahab\'s most famous photo spot. Comfortable rooms with sea view, optional breakfast at the famous Mojito Café.',
    images: [PLACEHOLDER_IMAGES.dahab1, PLACEHOLDER_IMAGES.diving], rating: 4.3,
    location: 'الممشى السياحي · صف أول بحر · اللايت هاوس', location_ar: 'الممشى السياحي · صف أول بحر · اللايت هاوس', location_en: 'Promenade · First Row · Lighthouse',
    amenities_ar: ['إطلالة بحر مباشرة', 'كافيه على البحر', 'واي فاي', 'تكييف'], amenities_en: ['Direct Sea View', 'Seaside Café', 'WiFi', 'AC'],
    price_per_night: 650, price_4day: 2650, price_5day: 3200, is_active: true, created_at: new Date().toISOString(),
  },

  /* ═══════════════ Standard ═══════════════ */
  {
    id: '4', name_ar: 'فندق موخيتو', name_en: 'Mojito Hotel Standard', type: 'hotel', tier: 'standard',
    description_ar: 'غرف فندقية حديثة بأعلى مستوى من الراحة في موقع اللايت هاوس — صف أول بحر. كافيه موخيتو الشهير مباشرة تحتك، والفطار اختياري بتكلفة بسيطة على البحر. من أشهر أماكن الإقامة وأكثرها طلباً في دهب.',
    description_en: 'Modern hotel rooms with top-tier comfort in the Lighthouse area — first row on the sea. The famous Mojito Café right below, optional breakfast at a small cost right on the water. One of Dahab\'s most requested stays.',
    images: [PLACEHOLDER_IMAGES.dahab1, PLACEHOLDER_IMAGES.diving], rating: 4.4,
    location: 'اللايت هاوس · صف أول بحر · دهب', location_ar: 'اللايت هاوس · صف أول بحر · دهب', location_en: 'Lighthouse · First Row · Dahab',
    amenities_ar: ['غرف حديثة', 'إطلالة بحر', 'واي فاي', 'تكييف', 'كافيه'], amenities_en: ['Modern Rooms', 'Sea View', 'WiFi', 'AC', 'Café'],
    price_per_night: 800, price_4day: 3100, price_5day: 3750, is_active: true, created_at: new Date().toISOString(),
  },
  {
    id: '5', name_ar: 'دلتا دهب', name_en: 'Delta Dahab', type: 'hotel', tier: 'standard',
    description_ar: 'فندق بحمام سباحة في قلب الممشى السياحي — مش هتحتاج تتحرك كتير عشان توصل لأي حاجة. فطار ومشروبات شاملة طول اليوم، وموقع مركزي يخليك في نص الحدث. مثالي للي عايزين راحة وقرب من كل حاجة.',
    description_en: 'A hotel with a swimming pool in the heart of the promenade — you won\'t need to go far for anything. Breakfast and drinks included all day, central location keeps you in the middle of everything. Ideal for those who want comfort and proximity.',
    images: [PLACEHOLDER_IMAGES.dahab2, PLACEHOLDER_IMAGES.dahab3], rating: 4.2,
    location: 'قلب الممشى السياحي · دهب', location_ar: 'قلب الممشى السياحي · دهب', location_en: 'Heart of Promenade · Dahab',
    amenities_ar: ['حمام سباحة', 'فطار ومشروبات', 'واي فاي', 'تكييف', 'موقع مركزي'], amenities_en: ['Swimming Pool', 'Breakfast & Drinks', 'WiFi', 'AC', 'Central Location'],
    price_per_night: 900, price_4day: 3450, price_5day: 4250, is_active: true, created_at: new Date().toISOString(),
  },
  {
    id: '6', name_ar: 'ديزرت هوتيل', name_en: 'Desert Hotel', type: 'hotel', tier: 'standard',
    description_ar: 'طابع بدوي أصيل وروح سيناء الحقيقية في فندق هادي بعيد عن صخب الممشى — لكن قريب من كل حاجة. تجربة مختلفة ما بين صحراء دهب وشواطئها، للمسافر اللي بيدور على هدوء وخصوصية.',
    description_en: 'Authentic Bedouin character and real Sinai spirit in a quiet hotel away from the promenade buzz — yet close to everything. A different experience between Dahab\'s desert and beaches, for the traveler seeking peace and privacy.',
    images: [PLACEHOLDER_IMAGES.desert1, PLACEHOLDER_IMAGES.desert2], rating: 4.3,
    location: 'دهب · طابع بدوي · قريب من البحر', location_ar: 'دهب · طابع بدوي · قريب من البحر', location_en: 'Dahab · Bedouin Style · Near Beach',
    amenities_ar: ['هدوء وخصوصية', 'طابع بدوي', 'واي فاي', 'تكييف', 'قريب من البحر'], amenities_en: ['Quiet & Private', 'Bedouin Style', 'WiFi', 'AC', 'Near Beach'],
    price_per_night: 900, price_4day: 3500, price_5day: 4400, is_active: true, created_at: new Date().toISOString(),
  },
  {
    id: '7', name_ar: 'بيت كابانا (شقق خاصة)', name_en: 'Cabana House (Private Apartment)', type: 'chalet', tier: 'standard',
    description_ar: 'شقق خاصة بالكامل في قلب العسلة الهادية — مطبخ، صالة، وخصوصية تامة. 5 دقائق مشي وانت على البحر. الفرد التالت والرابع بنص السعر — مثالي للجروبات والعائلات اللي عايزة مساحتها واستقلاليتها.',
    description_en: 'Fully private apartments in the quiet Assala area — kitchen, living room, and complete privacy. 5 minutes walk to the beach. 3rd and 4th person at half price — ideal for groups and families who want their own space.',
    images: [PLACEHOLDER_IMAGES.dahab3, PLACEHOLDER_IMAGES.dahab1], rating: 4.4,
    location: 'العسلة · 5 دقائق على البحر · دهب', location_ar: 'العسلة · 5 دقائق على البحر · دهب', location_en: 'Assala · 5min to Beach · Dahab',
    amenities_ar: ['شقة كاملة', 'مطبخ مجهز', 'خصوصية تامة', 'واي فاي', 'قريب من البحر'], amenities_en: ['Full Apartment', 'Equipped Kitchen', 'Full Privacy', 'WiFi', 'Near Beach'],
    price_per_night: 850, price_4day: 3300, price_5day: 4100, is_active: true, created_at: new Date().toISOString(),
  },
  {
    id: '8', name_ar: 'صن سيت لاكجري هوتيل', name_en: 'Sunset Luxury Hotel', type: 'hotel', tier: 'standard',
    description_ar: 'فندق راقي في قلب الممشى السياحي — اسمه مش صدفة: أحلى إطلالة غروب في دهب من التراس والغرف. فطار يومي شامل يبدأ يومك على راحتك، وغرف فندقية مريحة بديكور دافئ وعصري.',
    description_en: 'An upscale hotel in the heart of the promenade — the name is no coincidence: the best sunset view in Dahab from the terrace and rooms. Daily breakfast included to start your day right, comfortable rooms with warm modern decor.',
    images: [PLACEHOLDER_IMAGES.dahab1, PLACEHOLDER_IMAGES.dahab2], rating: 4.5,
    location: 'الممشى السياحي · إطلالة الغروب · دهب', location_ar: 'الممشى السياحي · إطلالة الغروب · دهب', location_en: 'Promenade · Sunset View · Dahab',
    amenities_ar: ['فطار يومي شامل', 'إطلالة غروب', 'واي فاي', 'تكييف', 'تراس'], amenities_en: ['Daily Breakfast', 'Sunset View', 'WiFi', 'AC', 'Terrace'],
    price_per_night: 1050, price_4day: 4100, price_5day: 5000, is_active: true, created_at: new Date().toISOString(),
  },

  /* ═══════════════ Premium ═══════════════ */
  {
    id: '9', name_ar: 'موخيتو بانوراما', name_en: 'Mojito Panorama Sea View', type: 'hotel', tier: 'premium',
    description_ar: 'Panoramic Sea View مباشر من الغرفة — من أكتر الغرف طلباً في دهب كلها. إطلالة 180 درجة على البحر الأحمر والجبال، وتفاصيل فندقية راقية. الفطار اختياري بتكلفة إضافية مع إطلالة لا توصف.',
    description_en: 'Direct Panoramic Sea View from your room — one of the most requested rooms in all of Dahab. 180-degree views of the Red Sea and mountains, with refined hotel details. Optional breakfast at extra cost with an indescribable view.',
    images: [PLACEHOLDER_IMAGES.dahab1, PLACEHOLDER_IMAGES.diving], rating: 4.7,
    location: 'اللايت هاوس · بانوراما سي فيو · دهب', location_ar: 'اللايت هاوس · بانوراما سي فيو · دهب', location_en: 'Lighthouse · Panorama Sea View · Dahab',
    amenities_ar: ['بانوراما سي فيو', 'غرف فاخرة', 'واي فاي', 'تكييف', 'كافيه'], amenities_en: ['Panorama Sea View', 'Luxury Rooms', 'WiFi', 'AC', 'Café'],
    price_per_night: 1100, price_4day: 4350, price_5day: 5550, is_active: true, created_at: new Date().toISOString(),
  },
  {
    id: '10', name_ar: 'موخيتو تيراس', name_en: 'Mojito Terrace Sea View', type: 'hotel', tier: 'premium',
    description_ar: 'أعلى مستوى في موخيتو — تراس خاص بيطل مباشرة على البحر الأحمر. الغرفة مصممة للعرسان والأزواج اللي بيدوروا على لحظة خاصة. الفطار اختياري بتكلفة إضافية مع sunrise على البحر من تراسك الخاص.',
    description_en: 'The highest tier at Mojito — private terrace overlooking the Red Sea directly. The room is designed for honeymooners and couples seeking a special moment. Optional breakfast at extra cost with sunrise on the sea from your private terrace.',
    images: [PLACEHOLDER_IMAGES.dahab2, PLACEHOLDER_IMAGES.diving], rating: 4.8,
    location: 'اللايت هاوس · تراس خاص على البحر · دهب', location_ar: 'اللايت هاوس · تراس خاص على البحر · دهب', location_en: 'Lighthouse · Private Terrace · Dahab',
    amenities_ar: ['تراس خاص', 'إطلالة بحر مباشرة', 'غرفة مميزة للعرسان', 'واي فاي', 'تكييف'], amenities_en: ['Private Terrace', 'Direct Sea View', 'Honeymoon Room', 'WiFi', 'AC'],
    price_per_night: 1200, price_4day: 4600, price_5day: 5900, is_active: true, created_at: new Date().toISOString(),
  },
  {
    id: '11', name_ar: 'فندق نسيمة', name_en: 'Nesima Hotel', type: 'hotel', tier: 'premium',
    description_ar: '4 نجوم — من أشهر وأعرق فنادق دهب. حمام سباحة ومطعم على البحر مباشرة، ومركز غوص Nesima الشهير. الغرف أنيقة وواسعة، ومناسب جداً للعائلات والغواصين اللي بيدوروا على إقامة مريحة بمستوى عالي.',
    description_en: '4 stars — one of Dahab\'s most famous and established hotels. Swimming pool and restaurant directly on the sea, plus the renowned Nesima Dive Center. Elegant, spacious rooms, ideal for families and divers seeking high-quality comfort.',
    images: [PLACEHOLDER_IMAGES.dahab3, PLACEHOLDER_IMAGES.diving], rating: 4.5,
    location: 'الممشى السياحي · صف أول · دهب', location_ar: 'الممشى السياحي · صف أول · دهب', location_en: 'Promenade · First Row · Dahab',
    amenities_ar: ['حمام سباحة', 'مطعم على البحر', 'مركز غوص', 'واي فاي', 'تكييف', 'فطار'], amenities_en: ['Swimming Pool', 'Seaside Restaurant', 'Dive Center', 'WiFi', 'AC', 'Breakfast'],
    price_per_night: 1200, price_4day: 4800, price_5day: 6000, is_active: true, created_at: new Date().toISOString(),
  },
  {
    id: '12', name_ar: 'أسالة سي فيو', name_en: 'Assala Sea View', type: 'chalet', tier: 'premium',
    description_ar: 'استوديوهات وشاليهات وأبارتمنتات مباشرة على البحر في العسلة الهادية — أبعد عن ضوضاء الممشى، أقرب للـ vibes الحقيقية. الفرد التالت والرابع بنص السعر — مثالي للجروبات والعرسان.',
    description_en: 'Studios, chalets, and apartments directly on the sea in quiet Assala — away from the promenade noise, closer to the real vibes. 3rd and 4th person at half price — ideal for groups and honeymooners.',
    images: [PLACEHOLDER_IMAGES.dahab1, PLACEHOLDER_IMAGES.dahab2], rating: 4.6,
    location: 'العسلة · مباشرة على البحر · دهب', location_ar: 'العسلة · مباشرة على البحر · دهب', location_en: 'Assala · Directly on Beach · Dahab',
    amenities_ar: ['مباشرة على البحر', 'مطبخ مجهز', 'خصوصية', 'واي فاي', 'تكييف'], amenities_en: ['Beachfront', 'Equipped Kitchen', 'Privacy', 'WiFi', 'AC'],
    price_per_night: 1400, price_4day: 5600, price_5day: 6600, is_active: true, created_at: new Date().toISOString(),
  },

  /* ═══════════════ Lagoon ═══════════════ */
  {
    id: '13', name_ar: 'كانيون / نوبيا آيلاند', name_en: 'Canyon / Nubia Island', type: 'hotel', tier: 'lagoon',
    description_ar: 'شاطئ رملي طبيعي في منطقة اللاجونا الخلابة — بعيد عن زحمة الممشى، قريب من الطبيعة. بوفيه فطار أوبن متنوع ومريح، وهدوء تام ما بين البحر والجبال. تجربة مختلفة لمن يريد دهب أخرى.',
    description_en: 'Natural sandy beach in the stunning Laguna area — away from the promenade crowds, close to nature. Open buffet breakfast, varied and comfortable, with total peace between the sea and mountains. A different experience for those seeking another Dahab.',
    images: [PLACEHOLDER_IMAGES.dahab1, PLACEHOLDER_IMAGES.diving], rating: 4.3,
    location: 'اللاجونا · شاطئ رملي · دهب', location_ar: 'اللاجونا · شاطئ رملي · دهب', location_en: 'Laguna · Sandy Beach · Dahab',
    amenities_ar: ['شاطئ رملي', 'بوفيه فطار', 'هدوء تام', 'واي فاي', 'تكييف'], amenities_en: ['Sandy Beach', 'Breakfast Buffet', 'Total Quiet', 'WiFi', 'AC'],
    price_per_night: 1050, price_4day: 4200, price_5day: 5200, is_active: true, created_at: new Date().toISOString(),
  },
  {
    id: '14', name_ar: 'باندا دهب ريزورت', name_en: 'Panda Dahab Resort', type: 'hotel', tier: 'lagoon',
    description_ar: 'ريزورت على شاطئ رملي في اللاجونا — أجواء رايقة وخدمة فندقية متكاملة. فطار شامل يومياً، ومساحات خضراء واسعة. مناسب للعائلات والجروبات اللي عايزة تستمتع بالبحر والهدوء بعيد عن الصخب.',
    description_en: 'Resort on a sandy beach in the Laguna — chill vibes with full hotel service. Daily breakfast included, spacious green areas. Suitable for families and groups who want to enjoy the sea and tranquility away from the buzz.',
    images: [PLACEHOLDER_IMAGES.dahab2, PLACEHOLDER_IMAGES.diving], rating: 4.4,
    location: 'اللاجونا · شاطئ رملي · دهب', location_ar: 'اللاجونا · شاطئ رملي · دهب', location_en: 'Laguna · Sandy Beach · Dahab',
    amenities_ar: ['شاطئ رملي', 'فطار شامل', 'مساحات خضراء', 'واي فاي', 'تكييف', 'مناسب للعائلات'], amenities_en: ['Sandy Beach', 'Breakfast Included', 'Green Areas', 'WiFi', 'AC', 'Family-Friendly'],
    price_per_night: 1200, price_4day: 4800, price_5day: 6000, is_active: true, created_at: new Date().toISOString(),
  },
  {
    id: '15', name_ar: 'جنة سيناء ريزورت', name_en: 'Ganet Sinai Resort', type: 'hotel', tier: 'lagoon',
    description_ar: 'صف أول في اللاجونا — مباشر على الشاطئ الرملي بمياه فيروزية. بوفيه فطار أوبن يومياً واسع ومتنوع، وغرف Deluxe Sea View متاحة بسعر إضافي. من أجمل مواقع اللاجونا وأكثرها طلباً.',
    description_en: 'First row in the Laguna — directly on the sandy beach with turquoise waters. Daily open breakfast buffet, wide and varied. Deluxe Sea View rooms available at extra cost. One of the most beautiful and requested spots in the Laguna.',
    images: [PLACEHOLDER_IMAGES.diving, PLACEHOLDER_IMAGES.dahab3], rating: 4.5,
    location: 'اللاجونا · صف أول · دهب', location_ar: 'اللاجونا · صف أول · دهب', location_en: 'Laguna · First Row · Dahab',
    amenities_ar: ['صف أول بحر', 'بوفيه فطار', 'ديلوكس سي فيو', 'واي فاي', 'تكييف'], amenities_en: ['First Row Beach', 'Breakfast Buffet', 'Deluxe Sea View', 'WiFi', 'AC'],
    price_per_night: 1300, price_4day: 5200, price_5day: 6600, is_active: true, created_at: new Date().toISOString(),
  },
  {
    id: '16', name_ar: 'إيكوتيل باي فيو', name_en: 'Ecotel Bay View Resort', type: 'hotel', tier: 'lagoon',
    description_ar: '4 نجوم في منطقة الثري بولز — من أجمل بقاع دهب وأكثرها هدوءاً. Half Board يومياً يشمل فطار وعشاء في الريزورت، وشاطئ بحري مباشر على مياه الثري بولز الفيروزية. تجربة فندقية راقية في موقع استثنائي.',
    description_en: '4 stars in the Three Pools area — one of Dahab\'s most beautiful and peaceful spots. Daily Half Board with breakfast and dinner at the resort, direct beach on the turquoise waters of Three Pools. Upscale hotel experience in an exceptional location.',
    images: [PLACEHOLDER_IMAGES.dahab1, PLACEHOLDER_IMAGES.diving], rating: 4.7,
    location: 'الثري بولز · صف أول · دهب', location_ar: 'الثري بولز · صف أول · دهب', location_en: 'Three Pools · First Row · Dahab',
    amenities_ar: ['Half Board', 'شاطئ خاص', '4 نجوم', 'واي فاي', 'تكييف', 'مطعم'], amenities_en: ['Half Board', 'Private Beach', '4 Stars', 'WiFi', 'AC', 'Restaurant'],
    price_per_night: 2300, price_4day: 9100, price_5day: 11800, is_active: true, created_at: new Date().toISOString(),
  },
  {
    id: '17', name_ar: 'ريتاك قناي', name_en: 'Retac Qunay Resort', type: 'hotel', tier: 'lagoon',
    description_ar: '5 نجوم في أفضل موقع — بين الثري بولز واللاجونا. Half Board يومياً في مطعم ريزورت متميز، وغرف Deluxe وSea View. تجربة فندقية فاخرة تجمع بين أفضل ما في دهب: البحر، الهدوء، والخدمة الممتازة.',
    description_en: '5 stars in the best location — between Three Pools and the Laguna. Daily Half Board at a distinguished resort restaurant, Deluxe and Sea View rooms. A luxurious hotel experience combining the best of Dahab: sea, tranquility, and excellent service.',
    images: [PLACEHOLDER_IMAGES.dahab2, PLACEHOLDER_IMAGES.diving], rating: 4.8,
    location: 'بين الثري بولز واللاجونا · دهب', location_ar: 'بين الثري بولز واللاجونا · دهب', location_en: 'Between Three Pools & Laguna · Dahab',
    amenities_ar: ['5 نجوم', 'Half Board', 'ديلوكس سي فيو', 'واي فاي', 'مسبح', 'مطعم فاخر'], amenities_en: ['5 Stars', 'Half Board', 'Deluxe Sea View', 'WiFi', 'Pool', 'Fine Dining'],
    price_per_night: 2400, price_4day: 9600, price_5day: 12400, is_active: true, created_at: new Date().toISOString(),
  },
  {
    id: '18', name_ar: 'دهب لاجون ريزورت', name_en: 'Dahab Lagoon Resort', type: 'hotel', tier: 'lagoon',
    description_ar: 'الأفخم والأرقى في دهب — 5 نجوم على شاطئ رملي خاص في اللاجونا الساحرة. Half Board في مطعم مستوى عالمي على البحر، وفيلات وأجنحة فاخرة بمستوى لا يُقارن. للتجربة اللي تستحق كل قرش.',
    description_en: 'The most luxurious in Dahab — 5 stars on a private sandy beach in the enchanting Laguna. Half Board at a world-class seaside restaurant, with luxurious villas and suites at an incomparable level. For the experience worth every penny.',
    images: [PLACEHOLDER_IMAGES.dahab3, PLACEHOLDER_IMAGES.diving], rating: 4.9,
    location: 'اللاجونا · 5 نجوم · دهب', location_ar: 'اللاجونا · 5 نجوم · دهب', location_en: 'Laguna · 5 Stars · Dahab',
    amenities_ar: ['5 نجوم', 'Half Board', 'شاطئ خاص', 'فيلات فاخرة', 'مطعم عالمي', 'مسبح'], amenities_en: ['5 Stars', 'Half Board', 'Private Beach', 'Luxury Villas', 'World-Class Restaurant', 'Pool'],
    price_per_night: 3000, price_4day: 12100, price_5day: 15800, is_active: true, created_at: new Date().toISOString(),
  },
]

/* ═══════════════ Sinai Trips ═══════════════ */
export const MOCK_SINAI_TRIPS: SinaiTrip[] = [
  {
    id: 't1', name_ar: 'سنوركلينج في البلوهول وأبو جالوم', name_en: 'Snorkeling at Blue Hole & Abu Galum',
    description_ar: 'رحلة بحرية ليوم كامل لأشهر مواقع الغوص والسنوركلينج في العالم. البلوهول، أبو جالوم، و blue lagoon — ثلاثة أماكن ساحرة في يوم واحد مع غداء بدوي ومشروبات.',
    description_en: 'Full-day sea trip to the world\'s most famous dive and snorkel sites. Blue Hole, Abu Galum, and Blue Lagoon — three stunning spots in one day with Bedouin lunch and drinks.',
    category_ar: 'بحر ومغامرة', category_en: 'Adventure & Sea',
    images: [PLACEHOLDER_IMAGES.dahab2, PLACEHOLDER_IMAGES.diving],
    duration: 'يوم كامل (8 ساعات)', duration_en: 'Full Day (8 hours)',
    price: 450,
    includes_ar: ['انتقالات من وإلى الفندق', 'معدات السنوركل', 'غداء بدوي', 'مرشد سياحي'],
    includes_en: ['Hotel Transfers', 'Snorkeling Gear', 'Bedouin Lunch', 'Tour Guide'],
    is_active: true, created_at: new Date().toISOString(),
  },
  {
    id: 't2', name_ar: 'جبل موسى وسانت كاترين', name_en: 'Mount Sinai & St. Catherine',
    description_ar: 'رحلة ليلية لمشاهدة الشروق من أعلى قمة في سيناء. تسلق جبل موسى ليلاً، مشاهدة الشروق، ثم زيارة دير سانت كاترين التاريخي. تجربة روحانية لا تُنسى.',
    description_en: 'Night trip to watch sunrise from Sinai\'s highest peak. Night climb of Mount Sinai, sunrise viewing, then visit the historic St. Catherine Monastery. An unforgettable spiritual experience.',
    category_ar: 'ديني وجبلي', category_en: 'Religious & Mountain Trek',
    images: [PLACEHOLDER_IMAGES.mountain, PLACEHOLDER_IMAGES.desert2],
    duration: 'رحلة ليلية (12 ساعة)', duration_en: 'Night Trip (12 hours)',
    price: 650,
    includes_ar: ['انتقالات بباص حديث', 'دليل بدوي مرخص', 'تذاكر دخول المحمية', 'مشروب دافئ'],
    includes_en: ['Modern Bus Transfer', 'Licensed Bedouin Guide', 'Reserve Entry Tickets', 'Hot Drink'],
    is_active: true, created_at: new Date().toISOString(),
  },
  {
    id: 't3', name_ar: 'سفاري وادي قني والوشواشي', name_en: 'Wadi Qnai & Washwashi Safari',
    description_ar: 'مغامرة صحراوية وسط جبال سيناء الملونة. جيب 4x4 لوديان قني والوشواشي، سباحة في عيون مائية طبيعية بين الجبال، وغداء بدوي تحت الشمس.',
    description_en: 'Desert adventure through Sinai\'s colored mountains. 4x4 jeep to Wadi Qnai and Washwashi, swimming in natural springs between mountains, and Bedouin lunch under the sun.',
    category_ar: 'سفاري وجواهر مخفية', category_en: 'Safari & Hidden Gems',
    images: [PLACEHOLDER_IMAGES.desert1, PLACEHOLDER_IMAGES.desert2],
    duration: 'نصف يوم (5 ساعات)', duration_en: 'Half Day (5 hours)',
    price: 500,
    includes_ar: ['سيارات جيب 4x4', 'دليل خبير', 'مياه ومشروبات', 'غداء بدوي'],
    includes_en: ['4x4 Jeep Transportation', 'Expert Guide', 'Water & Drinks', 'Bedouin Lunch'],
    is_active: true, created_at: new Date().toISOString(),
  },
]

/* ═══════════════ Community Posts ═══════════════ */
export const MOCK_COMMUNITY_POSTS = [
  {
    id: 'p1', title_ar: 'ليه دهب مختلفة عن أي مكان تاني في مصر', title_en: 'Why Dahab is Different from Anywhere Else in Egypt',
    content_ar: 'دهب مش مجرد مدينة ساحلية — دي حالة. مزيج فريد من البحر والجبل والصحراء في مكان واحد. الجو مختلف، الناس مختلفة، والطاقة مختلفة. في البوست ده هنحكي عن اللي بيخلي دهب مميزة عن أي مكان تاني.',
    content_en: 'Dahab isn\'t just a coastal town — it\'s a state of mind. A unique blend of sea, mountain, and desert in one place. The vibe is different, the people are different, the energy is different. In this post we tell you what makes Dahab unlike anywhere else.',
    category: 'blog', image_url: PLACEHOLDER_IMAGES.dahab1,
    is_pinned: true, sort_order: 1,
    created_at: new Date('2026-08-01').toISOString(),
  },
  {
    id: 'p2', title_ar: 'منطقة وادي الوشواشي — الجوهرة المخفية', title_en: 'Wadi Washwashi — The Hidden Gem',
    content_ar: 'وادي سري في قلب جبال سيناء، ما بين مياه فيروزية وصخور جرانيتية ملونة. المكان ده مش كل الناس تعرفه، وده اللي بيخليه مميز. في البوست ده هنشرح إزاي توصل له وأفضل وقت تزوره.',
    content_en: 'A secret valley in the heart of Sinai\'s mountains, between turquoise waters and colored granite rocks. Not everyone knows this place, and that\'s what makes it special. In this post we explain how to get there and the best time to visit.',
    category: 'hidden-gems', image_url: PLACEHOLDER_IMAGES.desert1,
    is_pinned: false, sort_order: 2,
    created_at: new Date('2026-07-28').toISOString(),
  },
  {
    id: 'p3', title_ar: 'أول مرة في دهب؟ دليلك الكامل', title_en: 'First Time in Dahab? Your Complete Guide',
    content_ar: 'لو دي أول مرة ليك في دهب، البوست ده معمول عشانك. من أفضل وقت للزيارة، لإزاي توصل، لأفضل الأماكن للإقامة، وأهم الأنشطة اللي متضيعش. دليل شامل بيجاوب على كل أسئلتك.',
    content_en: 'If this is your first time in Dahab, this post was made for you. From the best time to visit, to how to get there, to the best places to stay, and the must-do activities. A comprehensive guide that answers all your questions.',
    category: 'dahab-guide', image_url: PLACEHOLDER_IMAGES.dahab2,
    is_pinned: false, sort_order: 3,
    created_at: new Date('2026-07-20').toISOString(),
  },
]